[2023-03-02T22:44:09.532+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: api_dag.create_table scheduled__2023-03-01T00:00:00+00:00 [queued]>
[2023-03-02T22:44:09.544+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: api_dag.create_table scheduled__2023-03-01T00:00:00+00:00 [queued]>
[2023-03-02T22:44:09.544+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-03-02T22:44:09.544+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 2
[2023-03-02T22:44:09.544+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-03-02T22:44:09.560+0000] {taskinstance.py:1300} INFO - Executing <Task(PostgresOperator): create_table> on 2023-03-01 00:00:00+00:00
[2023-03-02T22:44:09.615+0000] {standard_task_runner.py:55} INFO - Started process 33776 to run task
[2023-03-02T22:44:09.618+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'api_dag', 'create_table', 'scheduled__2023-03-01T00:00:00+00:00', '--job-id', '16', '--raw', '--subdir', 'DAGS_FOLDER/api_dag.py', '--cfg-path', '/tmp/tmpo_jgl365']
[2023-03-02T22:44:09.619+0000] {standard_task_runner.py:83} INFO - Job 16: Subtask create_table
[2023-03-02T22:44:09.674+0000] {task_command.py:388} INFO - Running <TaskInstance: api_dag.create_table scheduled__2023-03-01T00:00:00+00:00 [running]> on host 9893918ef534
[2023-03-02T22:44:09.740+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Airflow
AIRFLOW_CTX_DAG_ID=api_dag
AIRFLOW_CTX_TASK_ID=create_table
AIRFLOW_CTX_EXECUTION_DATE=2023-03-01T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-03-01T00:00:00+00:00
[2023-03-02T22:44:09.741+0000] {sql.py:254} INFO - Executing: 
            drop table if exists rates;
            create table rates(
                rate float not null,
                symbol text not null
            );
        
[2023-03-02T22:44:09.749+0000] {base.py:73} INFO - Using connection ID 'postgres' for task execution.
[2023-03-02T22:44:09.939+0000] {base.py:73} INFO - Using connection ID 'postgres' for task execution.
[2023-03-02T22:44:09.942+0000] {sql.py:375} INFO - Running statement: 
            drop table if exists rates;
            create table rates(
                rate float not null,
                symbol text not null
            );
        , parameters: None
[2023-03-02T22:44:09.953+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/operators/sql.py", line 266, in execute
    **extra_kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 349, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 380, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "pg_type_typname_nsp_index"
DETAIL:  Key (typname, typnamespace)=(rates, 2200) already exists.

[2023-03-02T22:44:09.963+0000] {taskinstance.py:1323} INFO - Marking task as UP_FOR_RETRY. dag_id=api_dag, task_id=create_table, execution_date=20230301T000000, start_date=20230302T224409, end_date=20230302T224409
[2023-03-02T22:44:09.975+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 16 for task create_table (duplicate key value violates unique constraint "pg_type_typname_nsp_index"
DETAIL:  Key (typname, typnamespace)=(rates, 2200) already exists.
; 33776)
[2023-03-02T22:44:09.991+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-03-02T22:44:10.007+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
